### PR TITLE
MTM-49181 fix for alarm, event, audit representation equals on source

### LINKED ISSUE #212: Problem with com.cumulocity.rest.representation.alarm.AlarmRepresentation
We updated to Version Cumulocity SDK Version 1015.77.0.
There was a change in the AlarmRepresentation-Class. It calls super for the equals and hashcode methode now. In our old version it does not call super for equals and hashcode. 
The parent class has an attribute of Type ManagedObjectRepresentation. Because of super call of hashcode and equals and the equals and hashcode implementation of the super class(EventRepresentation) the equals and hashcode methode of the ManagedObjectRepresentation class is called. The ManagedObjectRepresentation class does not implement equals and hashcode. The two compared ManagedObjectRepresentation classes have the same id, but they have not the same address in memory. The equals and hashcode method is not implemented and so the result of equals methode is false and so the two Alarmrepresentation Objects are also unequal. Why does the ManagedObjectRepresentation-Class not implement the equals and hashcode methode???

### PR DESCRIPTION
**Pull request by jkot-c8y**

### CODE REVIEW

File: java-client-model/src/main/java/com/cumulocity/rest/representation/event/EventRepresentation.java [hunk 1]
```diff
@@ -38,8 +38,10 @@ public class EventRepresentation extends AbstractExtensibleRepresentation implem
 
     private String text;
 
+    @EqualsAndHashCode.Exclude
     private ManagedObjectRepresentation managedObject;
 
+    @EqualsAndHashCode.Exclude
     private ExternalIDRepresentation externalSource;
```
Comment (jkot-c8y) [inline java-client-model/src/main/java/com/cumulocity/rest/representation/event/EventRepresentation.java:45]: This is not needed in clients-java, from outside will be always empty.

**Review by kaczynskid-sag — DISMISSED** [review]

**Review by karol-c8y — DISMISSED** [review]
Missing tests for events?

**Review by karol-c8y — APPROVED** [review]

**Review by kaczynskid-sag — APPROVED** [review]

**Comment by c8y-kh4mell** [comment]
@jkot-softwareag requested to merge it forcibly.
